### ISSUE TITLE
Scroll inside menu not possible

### ISSUE THREAD

**Issue by Graahf** [grubersjoe/slide-menu#14]
Hey :)

Great plugin, but when the number of children excess the screenheight, it's not possible to scroll in the menu, to get to the last element :(

**Comment by vcoppolecchia** [comment]
Hey @Graahf, I think I can help here.

Inside the file `slide-menu.css` you can see this CSS property:
```CSS
.slide-menu {
    …
    overflow: hidden;
    …
}
```

I managed to solve the "issue" you mention this way:
```CSS
.slide-menu {
    …
    overflow-x: hidden;
    overflow-y: scroll;
    …
}
```
This way you're basically telling the container to scroll in the y (vertical) axis when the content si taller than the viewport height.

**Extra informations (not mandatory to solve your problem)**: you can edit the `slide-menu.css` file or the `slide-menu.scss` SASS file; you'll find both the files inside the npm package. Personally I've copy/pasted the .scss file and I'm compiling that one with all my others SASS chunks instead of editing it directly in the `node_modules/@grubersjoe/slide-menu/` folder.

Hope this will help you, bye!
